Change the destination location to product
error: packages/apps/MuPDF/Android.bp:20:24: unrecognized property "system_ext_specific"
error: packages/apps/MuPDF/Android.bp:41:24: unrecogni zed property "system_ext_specific
error: packages/apps/MuPDF/libs/Android.bp:20:24: unrecognized property "system_ext_specific"

- The system_ext partition was only officially introduced starting with Android 11.

Signed-off-by: Vhmit <viktor.9630@protonmail.com>